### ISSUE TITLE
Allow access to Hetzner infrastructure

### ISSUE THREAD

**Issue by ausias-armesto** [Rpc-h/infrastructure#46]
I cannot access to Hetzner infrastructure. Please add my public key to the 50 VM

````
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrci/6VRLBPR5lRwHcoEdoDAbF6gTWCabLNZx2nUbwl ausias
````

Also document somewhere in the repository, how those VM where installed.

**Comment by ausias-armesto** [comment]
@sitilge would you mind to document how you did everything?
How to add new public keys
How to execute Terraform and Ansible?

**Comment by Teebor-Choka** [comment]
> I executed a simple one-liner:
> 
> ```
>   tasks:
>     - name: Update the authorized keys
>       ansible.builtin.shell:
>         cmd: echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrci/6VRLBPR5lRwHcoEdoDAbF6gTWCabLNZx2nUbwl ausias" >> /root/.ssh/authorized_keys
> ```

Please, use the native ansible approach:
```yaml
- name: Copy SSH Keys 
  become: true
  authorized_key:
    user: "<your_user>"
    state: present
    key: "{{ lookup('file', item) }}"
loop: "{{ user_keys }}"
```
